const electron = require("electron");
window.md5 = require('md5');
window.theme = electron.remote.nativeTheme;
window.path = require("path");
window.app = electron.remote.app;
window.Store = require("./configs/store.config.js");
window.i18next = require('./configs/i18next.config');
window.fs = require('fs');
window.dialog = electron.remote.dialog;
