name: sleek
base: core18
summary: Todo app based on the todo.txt format for Linux, free and open-source
description: |
  sleek is an open-source todo app that makes use of the todo.txt format. sleeks GUI is modern and simple but still offers a decent set of functions which help users getting things done. sleek is available as a client for Windows, MacOS and Linux.

  Users can add contexts, projects, priorities, due dates or recurrences to their todos. These todo.txt attributes can then be used as filters or to group and sort the todo list.

  sleek manages and watches multiple todo.txt files continuously for changes, which makes it easy to integrate sleek with other todo.txt apps. Also users can switch between bright and dark mode and choose from multiple languages.

  Todos with due date or repeating todos will trigger notifications and completed todos can be hidden or archived into separate done.txt files. If users have tons of todos, a compact view can come in handy.

grade: stable
confinement: strict
icon: ./assets/icons/512x512.png
license: MIT
compression: lzo
architectures:
- build-on: amd64
- build-on: i386
- build-on: arm64
- build-on: armhf
apps:
  sleek:
    command: snap/command-chain/desktop-launch $SNAP/sleek/sleek --disable-gpu --no-sandbox
    environment:
      DISABLE_WAYLAND: 1
      TMPDIR: $XDG_RUNTIME_DIR
      PATH: "$SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH"
      SNAP_DESKTOP_RUNTIME: $SNAP/gnome-platform
      GTK_USE_PORTALS: 1
    extensions: [gnome-3-28]
    plugs:
    - home
    - browser-support
    - network
parts:
  sleek:
    plugin: nil
    build-environment:
    - PATH: "$PATH:$SNAPCRAFT_PART_BUILD/node_modules/.bin"
    build-snaps:
    - node/14/stable
    source: .
    override-build: |
      if [ -n "$http_proxy" ]; then
        export ELECTRON_GET_USE_PROXY=1
        export GLOBAL_AGENT_HTTP_PROXY="${http_proxy}"
        export GLOBAL_AGENT_HTTPS_PROXY="${http_proxy}"
      fi

      yarn add electron-packager@latest
      yarn install
      electron-packager . --overwrite --platform=linux --output=release-build \
          --prune=true --out $SNAPCRAFT_PART_INSTALL/
      mv $SNAPCRAFT_PART_INSTALL/$SNAPCRAFT_PROJECT_NAME-linux-* \
          $SNAPCRAFT_PART_INSTALL/sleek

      VER=$(npm show sleek version)
      echo "VERSION $(npm show sleek version)"
      snapcraftctl set-version $VER
    stage-packages:
    - libnss3
  cleanup:
    after: [ sleek ]
    plugin: nil
    build-snaps: [ gnome-3-28-1804 ]
    override-prime: |
      cd sleek
      ls -l
      rm LICENSES.chromium.html
      rm chrome-sandbox
      ls -l
      set -eux
      for snap in "gnome-3-28-1804"; do  # List all content-snaps you're using here
        cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" "$SNAPCRAFT_PRIME/usr/{}" \;
      done
      for CRUFT in bug lintian man; do
        rm -rf $SNAPCRAFT_PRIME/usr/share/$CRUFT
      done
      find $SNAPCRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
      find $SNAPCRAFT_PRIME/usr/share -type d -empty -delete
