name: sleek
base: core18
version: "1.1.9"
summary: todo.txt manager for Linux, free and open-source (FOSS)
description: |
  sleek is an open-source (FOSS) todo manager based on the todo.txt syntax. Stripped down to only the most necessary features, and with a clean and simple interface, sleek aims to help you focus on getting things done.

  All classic todo.txt attributes are supported and enhanced by additional features. Creating todos is straightforward, and tag-based filtering in tandem with highly customisable grouping and smart full-text search allow for rapid information retrieval. Completed todos can be hidden or archived into separate done.txt files. Easy integration with other todo.txt apps is facilitated by continuously scanning todo.txt files for changes.

  sleek is available for Windows, MacOS and Linux, and in several languages. For a detailed list of features, see below.

grade: stable
confinement: strict
icon: ./assets/icons/512x512.png
license: MIT
compression: lzo
architectures:
- build-on: amd64
- build-on: i386
- build-on: arm64
- build-on: armhf
apps:
  sleek:
    command: snap/command-chain/desktop-launch $SNAP/sleek/sleek --disable-gpu --no-sandbox
    environment:
      DISABLE_WAYLAND: 1
      TMPDIR: $XDG_RUNTIME_DIR
      PATH: "$SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH"
      SNAP_DESKTOP_RUNTIME: $SNAP/gnome-platform
      GTK_USE_PORTALS: 1
    extensions: [gnome-3-28]
    plugs:
    - home
    - browser-support
    - network
    - removable-media
parts:
  sleek:
    plugin: nil
    build-environment:
    - PATH: "$PATH:$SNAPCRAFT_PART_BUILD/node_modules/.bin"
    build-snaps:
    - node/14/stable
    source: .
    override-build: |
      if [ -n "$http_proxy" ]; then
        export ELECTRON_GET_USE_PROXY=1
        export GLOBAL_AGENT_HTTP_PROXY="${http_proxy}"
        export GLOBAL_AGENT_HTTPS_PROXY="${http_proxy}"
      fi

      yarn add electron-packager@latest
      yarn install
      electron-packager . --overwrite --platform=linux --output=release-build \
          --prune=true --out $SNAPCRAFT_PART_INSTALL/
      mv $SNAPCRAFT_PART_INSTALL/$SNAPCRAFT_PROJECT_NAME-linux-* \
          $SNAPCRAFT_PART_INSTALL/sleek
    stage-packages:
    - libnss3
  cleanup:
    after: [ sleek ]
    plugin: nil
    build-snaps: [ gnome-3-28-1804 ]
    override-prime: |
      cd sleek
      ls -l
      rm LICENSES.chromium.html
      rm chrome-sandbox
      ls -l
      set -eux
      for snap in "gnome-3-28-1804"; do  # List all content-snaps you're using here
        cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" "$SNAPCRAFT_PRIME/usr/{}" \;
      done
      for CRUFT in bug lintian man; do
        rm -rf $SNAPCRAFT_PRIME/usr/share/$CRUFT
      done
      find $SNAPCRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
      find $SNAPCRAFT_PRIME/usr/share -type d -empty -delete
