name: Prepare releases

on:
  push:
    tags: ['v*.*.*']

permissions:
  contents: write

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 26
          cache: npm
      - uses: actions/cache@v6
        with:
          path: ~/.cache/electron
          key: mac-electron-${{ hashFiles('**/package-lock.json') }}
      - run: npm ci
      - run: npm run build
      - run: npx electron-builder --mac --publish always
        env:
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          GH_TOKEN: ${{ secrets.github_token }}

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 26
          cache: npm
      - uses: actions/cache@v6
        with:
          path: ~\AppData\Local\electron
          key: win-electron-${{ hashFiles('**/package-lock.json') }}
      - run: npm ci
      - run: npm run build
      - run: npx electron-builder --win --publish always
        env:
          GH_TOKEN: ${{ secrets.github_token }}

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 26
          cache: npm
      - uses: actions/cache@v6
        with:
          path: ~/.cache/electron
          key: linux-electron-${{ hashFiles('**/package-lock.json') }}
      - run: npm ci
      - run: npm run build
      - run: npx electron-builder --linux --publish always
        env:
          GH_TOKEN: ${{ secrets.github_token }}
